import {
  Workspace,
  MetricStat,
  ClientRevenueItem,
  TaskDueItem,
  DailyPerformancePoint,
  NotificationItem,
  LeadKanbanCard,
  GbpIssue,
  ClientApprovalItem,
  ActivityRecord,
  LayoutConfig,
  KpiDrilldownData,
} from "../types";

export const CURRENCY_RATES = {
  INR: { symbol: "₹", rate: 1, label: "INR (₹)" },
  USD: { symbol: "$", rate: 0.012, label: "USD ($)" },
  AED: { symbol: "د.إ", rate: 0.044, label: "AED (د.إ)" },
  EUR: { symbol: "€", rate: 0.011, label: "EUR (€)" },
};

export const DEFAULT_LAYOUT_CONFIG: LayoutConfig = {
  showOverviewGraph: true,
  showSocialCalendar: true,
  showGbpAudit: true,
  showCrmKanban: true,
  showApprovals: true,
  showUserFlow: true,
  compactKpiCards: false,
};

export const INITIAL_WORKSPACES: Workspace[] = [
  {
    id: "agency-hq",
    name: "Digivigee Digital",
    type: "agency",
    initials: "DD",
    activeProjectsCount: 48,
    mrr: "₹8,45,230",
    rawMrr: 845230,
  },
  {
    id: "abc-clinic",
    name: "ABC Clinic",
    clientName: "ABC Clinic (Surat, Gujarat)",
    type: "client",
    initials: "AC",
    healthScore: 82,
    activeProjectsCount: 6,
    mrr: "₹1,25,000",
    rawMrr: 125000,
  },
  {
    id: "wellcare-hospital",
    name: "Wellcare Hospital",
    clientName: "Wellcare Hospital",
    type: "client",
    initials: "WH",
    healthScore: 89,
    activeProjectsCount: 8,
    mrr: "₹95,000",
    rawMrr: 95000,
  },
  {
    id: "smile-dental",
    name: "Smile Dental Care",
    clientName: "Smile Dental Care",
    type: "client",
    initials: "SD",
    healthScore: 94,
    activeProjectsCount: 4,
    mrr: "₹75,000",
    rawMrr: 75000,
  },
  {
    id: "skin-bliss",
    name: "Skin Bliss Clinic",
    clientName: "Skin Bliss Clinic",
    type: "client",
    initials: "SB",
    healthScore: 78,
    activeProjectsCount: 5,
    mrr: "₹60,000",
    rawMrr: 60000,
  },
  {
    id: "fitlife-gym",
    name: "FitLife Gym",
    clientName: "FitLife Gym",
    type: "client",
    initials: "FL",
    healthScore: 85,
    activeProjectsCount: 7,
    mrr: "₹55,000",
    rawMrr: 55000,
  },
];

export const INITIAL_METRICS: MetricStat[] = [
  {
    id: "clients",
    label: "Total Clients",
    value: "32",
    change: "+12%",
    isPositive: true,
    color: "text-purple-600 dark:text-purple-400",
    bgColor: "bg-purple-50 border-purple-100",
    iconName: "users",
    sparklineData: [26, 27, 28, 29, 30, 31, 32],
    absoluteDelta: "+4 clients this month",
    rawNumericValue: 32,
    isCurrency: false,
  },
  {
    id: "projects",
    label: "Active Projects",
    value: "48",
    change: "+18%",
    isPositive: true,
    color: "text-emerald-600 dark:text-emerald-400",
    bgColor: "bg-emerald-50 border-emerald-100",
    iconName: "folder",
    sparklineData: [38, 40, 42, 43, 45, 46, 48],
    absoluteDelta: "+7 active campaigns",
    rawNumericValue: 48,
    isCurrency: false,
  },
  {
    id: "revenue",
    label: "Monthly Revenue",
    value: "₹8,45,230",
    change: "+22%",
    isPositive: true,
    color: "text-fuchsia-600 dark:text-fuchsia-400",
    bgColor: "bg-fuchsia-50 border-fuchsia-100",
    iconName: "trending",
    sparklineData: [6.8, 7.1, 7.3, 7.6, 7.9, 8.2, 8.45],
    absoluteDelta: "+₹1,52,400 vs last month",
    rawNumericValue: 845230,
    isCurrency: true,
  },
  {
    id: "approvals",
    label: "Pending Approvals",
    value: "24",
    change: "-8%",
    isPositive: true,
    color: "text-amber-600 dark:text-amber-400",
    bgColor: "bg-amber-50 border-amber-100",
    iconName: "check",
    sparklineData: [32, 30, 28, 29, 27, 25, 24],
    absoluteDelta: "4 require urgent review",
    rawNumericValue: 24,
    isCurrency: false,
  },
  {
    id: "posts",
    label: "Scheduled Posts",
    value: "156",
    change: "+35%",
    isPositive: true,
    color: "text-blue-600 dark:text-blue-400",
    bgColor: "bg-blue-50 border-blue-100",
    iconName: "calendar",
    sparklineData: [110, 118, 126, 134, 142, 148, 156],
    absoluteDelta: "+42 queued this week",
    rawNumericValue: 156,
    isCurrency: false,
  },
  {
    id: "tasks",
    label: "Open Tasks",
    value: "68",
    change: "+5%",
    isPositive: false,
    color: "text-rose-600 dark:text-rose-400",
    bgColor: "bg-rose-50 border-rose-100",
    iconName: "clock",
    sparklineData: [60, 62, 63, 65, 64, 66, 68],
    absoluteDelta: "12 due in next 48h",
    rawNumericValue: 68,
    isCurrency: false,
  },
];

export const INITIAL_TOP_CLIENTS: ClientRevenueItem[] = [
  {
    id: "c1",
    rank: 1,
    name: "ABC Clinic",
    revenue: "₹1,25,000",
    growth: "+20%",
    status: "scaling",
    mrrSharePercent: 14.8,
    category: "Healthcare & Surgical",
    tier: "Platinum Retainer",
    activeServices: ["SEO", "Ads", "Social"],
    isVerified: true,
    rawRevenueValue: 125000,
  },
  {
    id: "c2",
    rank: 2,
    name: "Wellcare Hospital",
    revenue: "₹95,000",
    growth: "+15%",
    status: "scaling",
    mrrSharePercent: 11.2,
    category: "Multispeciality Hospital",
    tier: "Gold Retainer",
    activeServices: ["GBP", "SEO", "CMS"],
    isVerified: true,
    rawRevenueValue: 95000,
  },
  {
    id: "c3",
    rank: 3,
    name: "Smile Dental Care",
    revenue: "₹75,000",
    growth: "+10%",
    status: "retained",
    mrrSharePercent: 8.9,
    category: "Dental Aesthetics",
    tier: "Standard Retainer",
    activeServices: ["Social", "Ads"],
    isVerified: true,
    rawRevenueValue: 75000,
  },
  {
    id: "c4",
    rank: 4,
    name: "Skin Bliss Clinic",
    revenue: "₹60,000",
    growth: "+2%",
    status: "retained",
    mrrSharePercent: 7.1,
    category: "Dermatology & Laser",
    tier: "Growth Retainer",
    activeServices: ["SEO", "Content"],
    isVerified: false,
    rawRevenueValue: 60000,
  },
  {
    id: "c5",
    rank: 5,
    name: "FitLife Gym",
    revenue: "₹55,000",
    growth: "+8%",
    status: "active",
    mrrSharePercent: 6.5,
    category: "Fitness & Wellness",
    tier: "Basic Retainer",
    activeServices: ["GBP", "Social"],
    isVerified: false,
    rawRevenueValue: 55000,
  },
];

export const INITIAL_TASKS_DUE: TaskDueItem[] = [
  {
    id: "t1",
    title: "Website Content Update",
    client: "ABC Clinic",
    dueDate: "May 27",
    priority: "critical",
    priorityLevel: "P1",
    urgency: "Due in 4h",
    assignee: { name: "Priya Patel", avatar: "PP" },
  },
  {
    id: "t2",
    title: "GBP Optimization",
    client: "Wellcare Hospital",
    dueDate: "May 28",
    priority: "high",
    priorityLevel: "P2",
    urgency: "Due tomorrow",
    assignee: { name: "Rahul Sharma", avatar: "RS" },
  },
  {
    id: "t3",
    title: "Monthly SEO Audit Report",
    client: "Smile Dental Care",
    dueDate: "May 29",
    priority: "medium",
    priorityLevel: "P3",
    urgency: "In 2 days",
    assignee: { name: "Amit Shah", avatar: "AS" },
  },
  {
    id: "t4",
    title: "Social Media 14-Day Calendar",
    client: "Skin Bliss Clinic",
    dueDate: "May 29",
    priority: "high",
    priorityLevel: "P2",
    urgency: "In 2 days",
    assignee: { name: "Sneha Nair", avatar: "SN" },
  },
];

export const DAILY_PERFORMANCE_POINTS: DailyPerformancePoint[] = [
  {
    date: "2024-05-20",
    dayLabel: "20 May",
    traffic: 11200,
    trafficFormatted: "11,200",
    leads: 32,
    leadsFormatted: "32 leads",
    revenue: 95000,
    revenueFormatted: "₹95,000",
    trafficChange: "+8%",
    leadsChange: "+5%",
    revenueChange: "+14%",
  },
  {
    date: "2024-05-21",
    dayLabel: "21 May",
    traffic: 12450,
    trafficFormatted: "12,450",
    leads: 38,
    leadsFormatted: "38 leads",
    revenue: 112000,
    revenueFormatted: "₹1,12,000",
    trafficChange: "+10%",
    leadsChange: "+12%",
    revenueChange: "+18%",
  },
  {
    date: "2024-05-22",
    dayLabel: "22 May",
    traffic: 14800,
    trafficFormatted: "14,800",
    leads: 46,
    leadsFormatted: "46 leads",
    revenue: 135000,
    revenueFormatted: "₹1,35,000",
    trafficChange: "+15%",
    leadsChange: "+18%",
    revenueChange: "+24%",
  },
  {
    date: "2024-05-23",
    dayLabel: "23 May",
    traffic: 13900,
    trafficFormatted: "13,900",
    leads: 42,
    leadsFormatted: "42 leads",
    revenue: 120000,
    revenueFormatted: "₹1,20,000",
    trafficChange: "-4%",
    leadsChange: "-6%",
    revenueChange: "-10%",
  },
  {
    date: "2024-05-24",
    dayLabel: "24 May",
    traffic: 16200,
    trafficFormatted: "16,200",
    leads: 54,
    leadsFormatted: "54 leads",
    revenue: 155000,
    revenueFormatted: "₹1,55,000",
    trafficChange: "+16%",
    leadsChange: "+22%",
    revenueChange: "+28%",
  },
  {
    date: "2024-05-25",
    dayLabel: "25 May",
    traffic: 17800,
    trafficFormatted: "17,800",
    leads: 58,
    leadsFormatted: "58 leads",
    revenue: 162000,
    revenueFormatted: "₹1,62,000",
    trafficChange: "+9%",
    leadsChange: "+8%",
    revenueChange: "+12%",
  },
  {
    date: "2024-05-26",
    dayLabel: "26 May",
    traffic: 18450,
    trafficFormatted: "18,450",
    leads: 62,
    leadsFormatted: "62 leads",
    revenue: 178000,
    revenueFormatted: "₹1,78,000",
    trafficChange: "+4%",
    leadsChange: "+6%",
    revenueChange: "+10%",
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-1",
    category: "approvals",
    title: "ABC Clinic Approved Creative Post",
    description: "Instagram graphic #402 approved with comment 'Looks great! Post it.'",
    time: "10m ago",
    unread: true,
    actionLabel: "View Deliverable",
  },
  {
    id: "notif-2",
    category: "payments",
    title: "Retainer Auto-Collected (Stripe)",
    description: "₹1,25,000 monthly retainer successfully debited from ABC Clinic.",
    time: "1h ago",
    unread: true,
    actionLabel: "View Invoice",
  },
  {
    id: "notif-3",
    category: "leads",
    title: "New Inbound Client Lead Captured",
    description: "Apex Multispeciality Hospital filled out CRM inquiry form for Local SEO.",
    time: "2h ago",
    unread: true,
    actionLabel: "Open in CRM",
  },
  {
    id: "notif-4",
    category: "system",
    title: "Google Business Profile: 3 New Reviews",
    description: "Wellcare Hospital received 3 five-star reviews on Google Maps.",
    time: "4h ago",
    unread: false,
    actionLabel: "Reply to Reviews",
  },
  {
    id: "notif-5",
    category: "approvals",
    title: "Smile Dental Requested Changes",
    description: "Creative team notified: 'Please update brand colors to Cyan #00C2CB.'",
    time: "6h ago",
    unread: false,
    actionLabel: "Open Editor",
  },
];

export const INITIAL_LEADS: LeadKanbanCard[] = [
  { id: "l1", title: "Dr. Mehta Clinic", location: "Surat", stage: "new", tags: ["Inbound", "Healthcare"], lastActivity: "1h ago" },
  { id: "l2", title: "Sihla Dental", location: "Surat", stage: "new", tags: ["Referral"], lastActivity: "3h ago" },
  { id: "l3", title: "Wellness Clinic", location: "Surat", stage: "contacted", tags: ["Meeting Done"], lastActivity: "4h ago" },
  { id: "l4", title: "Skin Care Studio", location: "Vadodara", stage: "contacted", tags: ["Discovery Call"], lastActivity: "1d ago" },
  { id: "l5", title: "Health Plus", location: "Surat", stage: "proposal", value: "₹1.2L Retainer", tags: ["Proposal Sent"], lastActivity: "2d ago" },
  { id: "l6", title: "ABC Clinic", location: "Surat", stage: "won", value: "₹1.25L Retainer", tags: ["Active Retainer"], lastActivity: "Ongoing" },
];

export const INITIAL_GBP_ISSUES: GbpIssue[] = [
  { id: "gbp1", title: "Business Category", description: "Primary category is sub-optimal for orthopedics ranking", severity: "critical", fixed: false },
  { id: "gbp2", title: "Business Description", description: "Description can be improved with high-intent keywords", severity: "warning", fixed: false },
  { id: "gbp3", title: "Photos & Media", description: "Add 5+ high-res clinic interior photos to boost rank", severity: "suggestion", fixed: false },
];

export const INITIAL_APPROVALS: ClientApprovalItem[] = [
  {
    id: "appr-1",
    platform: "Instagram",
    title: "Healthy lungs, happy life",
    caption: "Take care of your lungs today for a better tomorrow. Regular checkups keep you breathing easy! #LungHealth #HealthyLife",
    imageUrl: "/images/showcase/david_sterling.jpg",
    scheduledTime: "28 May 2024, 10:00 AM",
    status: "pending",
    comments: [],
  },
];

export const INITIAL_CLIENT_ACTIVITIES: ActivityRecord[] = [
  { id: "act1", text: "New 5-star review received on Google Maps", time: "2h ago", type: "review" },
  { id: "act2", text: "Instagram post published via Digivigee Hub", time: "5h ago", type: "social" },
  { id: "act3", text: "Weekly technical SEO audit completed (0 broken links)", time: "1d ago", type: "seo" },
  { id: "act4", text: "New patient consultation lead captured via Website Form", time: "1d ago", type: "lead" },
];

export const KPI_DRILLDOWN_MAP: Record<string, KpiDrilldownData> = {
  clients: {
    metricId: "clients",
    title: "Total Client Portals",
    value: "32 Active",
    change: "+12%",
    absoluteDelta: "+4 onboarded this month",
    description: "Active retainer clients across medical, hospital, and aesthetic verticals.",
    breakdown: [
      { label: "Healthcare & Hospitals", value: "14", share: 44, color: "bg-emerald-500" },
      { label: "Dental Clinics", value: "9", share: 28, color: "bg-blue-500" },
      { label: "Dermatology & Aesthetics", value: "6", share: 19, color: "bg-purple-500" },
      { label: "Fitness & Wellness", value: "3", share: 9, color: "bg-amber-500" },
    ],
    recentLogs: [
      { id: "log-1", title: "ABC Clinic contract renewed for 12 months", time: "Today 10:30 AM", status: "Active", client: "ABC Clinic" },
      { id: "log-2", title: "Apex Multispeciality onboarded into Gujarat tier", time: "Yesterday", status: "Onboarding", client: "Apex Hospital" },
      { id: "log-3", title: "FitLife Gym upgraded to Growth Retainer", time: "3 days ago", status: "Active", client: "FitLife Gym" },
    ],
  },
  projects: {
    metricId: "projects",
    title: "Active Campaigns & Roadmaps",
    value: "48 Running",
    change: "+18%",
    absoluteDelta: "+7 campaigns launched",
    description: "Multi-channel projects spanning SEO audits, Meta ad sets, and website builds.",
    breakdown: [
      { label: "Local SEO & GBP", value: "18", share: 38, color: "bg-blue-500" },
      { label: "Social Media Publishing", value: "15", share: 31, color: "bg-emerald-500" },
      { label: "Performance Paid Ads", value: "10", share: 21, color: "bg-purple-500" },
      { label: "Websites & Landing Pages", value: "5", share: 10, color: "bg-amber-500" },
    ],
    recentLogs: [
      { id: "log-p1", title: "Surat Local Pack SEO Sprint #4 completed", time: "2h ago", status: "Completed", client: "Wellcare Hospital" },
      { id: "log-p2", title: "Meta Ads ROAS campaign scaled to 4.2x", time: "5h ago", status: "Scaling", client: "Smile Dental" },
    ],
  },
  revenue: {
    metricId: "revenue",
    title: "Monthly Recurring Revenue (MRR)",
    value: "₹8,45,230",
    change: "+22%",
    absoluteDelta: "+₹1,52,400 vs previous month",
    description: "Consolidated agency retainers, recurring software add-ons, and performance fee payouts.",
    breakdown: [
      { label: "Monthly Retainer Subscriptions", value: "₹5,80,000", share: 69, color: "bg-emerald-500" },
      { label: "Performance ROAS Bonuses", value: "₹1,65,000", share: 20, color: "bg-purple-500" },
      { label: "Google Business & SEO Addons", value: "₹1,00,230", share: 11, color: "bg-blue-500" },
    ],
    recentLogs: [
      { id: "log-r1", title: "Stripe auto-collected ₹1,25,000 retainer", time: "1h ago", status: "Paid", client: "ABC Clinic" },
      { id: "log-r2", title: "Invoice #INV-2024-88 sent to Wellcare", time: "Yesterday", status: "Pending", client: "Wellcare Hospital" },
    ],
  },
  approvals: {
    metricId: "approvals",
    title: "Client Approval Pipeline",
    value: "24 Items",
    change: "-8%",
    absoluteDelta: "4 require urgent review within 24h",
    description: "Creatives, reels, and ad copy submitted to clients for one-click portal review.",
    breakdown: [
      { label: "Instagram & Facebook Posts", value: "14", share: 58, color: "bg-blue-500" },
      { label: "Meta Ad Creatives", value: "6", share: 25, color: "bg-purple-500" },
      { label: "Blog & SEO Articles", value: "4", share: 17, color: "bg-amber-500" },
    ],
    recentLogs: [
      { id: "log-a1", title: "Dr. Shah approved World Asthma Day reel", time: "10m ago", status: "Approved", client: "ABC Clinic" },
      { id: "log-a2", title: "Smile Dental requested color palette changes", time: "6h ago", status: "Changes Needed", client: "Smile Dental" },
    ],
  },
  posts: {
    metricId: "posts",
    title: "Scheduled Multi-Channel Posts",
    value: "156 Queued",
    change: "+35%",
    absoluteDelta: "+42 posts queued this week",
    description: "Automated social calendar across Instagram, Facebook, LinkedIn, and TikTok.",
    breakdown: [
      { label: "Instagram Reels & Grids", value: "72", share: 46, color: "bg-pink-500" },
      { label: "Facebook Community Posts", value: "44", share: 28, color: "bg-blue-600" },
      { label: "LinkedIn Case Studies", value: "28", share: 18, color: "bg-blue-400" },
      { label: "TikTok Video Snippets", value: "12", share: 8, color: "bg-emerald-500" },
    ],
    recentLogs: [
      { id: "log-s1", title: "Carousel #308 scheduled for May 28, 10:00 AM", time: "30m ago", status: "Scheduled", client: "Wellcare Hospital" },
      { id: "log-s2", title: "Orthodontics FAQ reel published automatically", time: "4h ago", status: "Published", client: "Smile Dental" },
    ],
  },
  tasks: {
    metricId: "tasks",
    title: "Agency Work & Tasks",
    value: "68 Open",
    change: "+5%",
    absoluteDelta: "12 tasks due in next 48 hours",
    description: "Internal agency sprint tasks assigned to developers, designers, and copywriters.",
    breakdown: [
      { label: "P1 Critical (Due <24h)", value: "12", share: 18, color: "bg-rose-500" },
      { label: "P2 High Priority", value: "28", share: 41, color: "bg-amber-500" },
      { label: "P3 Normal Pacing", value: "28", share: 41, color: "bg-blue-500" },
    ],
    recentLogs: [
      { id: "log-t1", title: "Priya Patel completed ABC Clinic landing redesign", time: "45m ago", status: "Completed", client: "ABC Clinic" },
      { id: "log-t2", title: "Rahul Sharma initiated GBP category audit", time: "2h ago", status: "In Progress", client: "Wellcare Hospital" },
    ],
  },
};
